project:
  type: website

website:
  title: "Movies Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: 
     light: cosmo
     dark: [cosmo, custom.scss]
    toc: true