project:
  type: website

website:
  title: "Movies Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: 
     light: custom.scss
     dark: [cosmo, custom.scss]
    toc: true